name: Sample job on push to main

on:
   push:
      branches: [ "main" ]

jobs:
   build:
     runs-on: ubuntu-latest
     strategy:
       matrix:
           os: [ubuntu-latest,windows-latest,macOS-latest]
     steps:
        - uses: actions/Checkout@v2
        - name: sample commands
          run: echo "hello"
